create database mix;
create database auctionmark;
create database chbenchmark;
create database epinions;
create database jpab;
create database link;
create database mysmixed;
create database noop;
create database seats;
create database smallbank;
create database tatp;
create database tpcc;
create database tpch;
create database twitter;
create database wikipedia;
create database ycsb;
GRANT ALL PRIVILEGES ON *.* TO 'user'@'localhost' IDENTIFIED BY 'password';
